import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { Buda } from "next/font/google";
import { Inter } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const buda = Buda({
  variable: "--font-buda",
  subsets: ["latin"],
  display: "swap",
  weight: "300",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Lois's art website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        className={`${inter.className}  ${buda.variable}  antialiased `}
      >
        <div className="max-w-7xl mx-auto overflow-hidden min-h-screen flex flex-col">
          <header>
            <Navbar />
          </header>
          <main className="grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
