import type { Metadata } from "next";
import "./globals.css";
import { Buda, Inter } from "next/font/google";

const buda = Buda({
  variable: "--font-buda",
  subsets: ["latin"],
  display: "swap",
  weight: "300",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Lois's art website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  ${buda.variable}  antialiased `}>
        {children}
      </body>
    </html>
  );
}
